FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3 \
    python3-pip 

RUN mkdir -p /home/root/shopify
WORKDIR /home/root/shopify

COPY . .

RUN pip3 install --no-cache-dir -r requirements.txt

RUN find -name "*.pyc" -delete
